version: '3.9'

services:
  approval-service:
    build:
      context: ./approval-service
      dockerfile: Dockerfile
    image: approvalservice
    container_name: approval-service
    ports:
      - "8101:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb_service
    networks:
      - spring

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    image: bookingservice
    container_name: booking-service
    ports:
      - "8102:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb_service
    networks:
      - spring

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    image: eventservice
    container_name: event-service
    ports:
      - "8103:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb_service
    networks:
      - spring

  mongodb_service:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27022:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - spring

  services-express:
    image: mongo-express
    container_name: services-express
    ports:
      - "8201:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb_service
    depends_on:
      - mongodb_service
    networks:
      - spring

networks:
  spring:
    driver: bridge
